# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN pacman --sync --noconfirm --refresh python2 bash sudo && ln -sf /usr/bin/python2 /usr/bin/python;
